echo Starting lexical tests
./lextest testcases/test1.tig > testresults/test1.txt
./lextest testcases/test2.tig > testresults/test2.txt
./lextest testcases/test3.tig > testresults/test3.txt
./lextest testcases/test4.tig > testresults/test4.txt
./lextest testcases/test5.tig > testresults/test5.txt
./lextest testcases/test6.tig > testresults/test6.txt
./lextest testcases/test7.tig > testresults/test7.txt
./lextest testcases/test8.tig > testresults/test8.txt
./lextest testcases/test9.tig > testresults/test9.txt
./lextest testcases/test10.tig > testresults/test10.txt
./lextest testcases/test11.tig > testresults/test11.txt
./lextest testcases/test12.tig > testresults/test12.txt
./lextest testcases/test13.tig > testresults/test13.txt
./lextest testcases/test14.tig > testresults/test14.txt
./lextest testcases/test15.tig > testresults/test15.txt
./lextest testcases/test16.tig > testresults/test16.txt
./lextest testcases/test17.tig > testresults/test17.txt
./lextest testcases/test18.tig > testresults/test18.txt
./lextest testcases/test19.tig > testresults/test19.txt
./lextest testcases/test20.tig > testresults/test20.txt
./lextest testcases/test21.tig > testresults/test21.txt
./lextest testcases/test22.tig > testresults/test22.txt
./lextest testcases/test23.tig > testresults/test23.txt
./lextest testcases/test24.tig > testresults/test24.txt
./lextest testcases/test25.tig > testresults/test25.txt
./lextest testcases/test26.tig > testresults/test26.txt
./lextest testcases/test27.tig > testresults/test27.txt
./lextest testcases/test28.tig > testresults/test28.txt
./lextest testcases/test29.tig > testresults/test29.txt
./lextest testcases/test30.tig > testresults/test30.txt
./lextest testcases/test31.tig > testresults/test31.txt
./lextest testcases/test32.tig > testresults/test32.txt
./lextest testcases/test33.tig > testresults/test33.txt
./lextest testcases/test34.tig > testresults/test34.txt
./lextest testcases/test35.tig > testresults/test35.txt
./lextest testcases/test36.tig > testresults/test36.txt
./lextest testcases/test37.tig > testresults/test37.txt
./lextest testcases/test38.tig > testresults/test38.txt
./lextest testcases/test39.tig > testresults/test39.txt
./lextest testcases/test40.tig > testresults/test40.txt
./lextest testcases/test41.tig > testresults/test41.txt
./lextest testcases/test42.tig > testresults/test42.txt
./lextest testcases/test43.tig > testresults/test43.txt
./lextest testcases/test44.tig > testresults/test44.txt
./lextest testcases/test45.tig > testresults/test45.txt
./lextest testcases/test46.tig > testresults/test46.txt
./lextest testcases/test47.tig > testresults/test47.txt
./lextest testcases/test48.tig > testresults/test48.txt
./lextest testcases/test49.tig > testresults/test49.txt
./lextest testcases/merge.tig > testresults/merge.txt
./lextest testcases/queens.tig > testresults/queens.txt

echo Finished lexical tests
