echo Starting lexical tests
./chap2/lextest testcases/test1.tig > testresults/chap2/test1.txt
./chap2/lextest testcases/test2.tig > testresults/chap2/test2.txt
./chap2/lextest testcases/test3.tig > testresults/chap2/test3.txt
./chap2/lextest testcases/test4.tig > testresults/chap2/test4.txt
./chap2/lextest testcases/test5.tig > testresults/chap2/test5.txt
./chap2/lextest testcases/test6.tig > testresults/chap2/test6.txt
./chap2/lextest testcases/test7.tig > testresults/chap2/test7.txt
./chap2/lextest testcases/test8.tig > testresults/chap2/test8.txt
./chap2/lextest testcases/test9.tig > testresults/chap2/test9.txt
./chap2/lextest testcases/test10.tig > testresults/chap2/test10.txt
./chap2/lextest testcases/test11.tig > testresults/chap2/test11.txt
./chap2/lextest testcases/test12.tig > testresults/chap2/test12.txt
./chap2/lextest testcases/test13.tig > testresults/chap2/test13.txt
./chap2/lextest testcases/test14.tig > testresults/chap2/test14.txt
./chap2/lextest testcases/test15.tig > testresults/chap2/test15.txt
./chap2/lextest testcases/test16.tig > testresults/chap2/test16.txt
./chap2/lextest testcases/test17.tig > testresults/chap2/test17.txt
./chap2/lextest testcases/test18.tig > testresults/chap2/test18.txt
./chap2/lextest testcases/test19.tig > testresults/chap2/test19.txt
./chap2/lextest testcases/test20.tig > testresults/chap2/test20.txt
./chap2/lextest testcases/test21.tig > testresults/chap2/test21.txt
./chap2/lextest testcases/test22.tig > testresults/chap2/test22.txt
./chap2/lextest testcases/test23.tig > testresults/chap2/test23.txt
./chap2/lextest testcases/test24.tig > testresults/chap2/test24.txt
./chap2/lextest testcases/test25.tig > testresults/chap2/test25.txt
./chap2/lextest testcases/test26.tig > testresults/chap2/test26.txt
./chap2/lextest testcases/test27.tig > testresults/chap2/test27.txt
./chap2/lextest testcases/test28.tig > testresults/chap2/test28.txt
./chap2/lextest testcases/test29.tig > testresults/chap2/test29.txt
./chap2/lextest testcases/test30.tig > testresults/chap2/test30.txt
./chap2/lextest testcases/test31.tig > testresults/chap2/test31.txt
./chap2/lextest testcases/test32.tig > testresults/chap2/test32.txt
./chap2/lextest testcases/test33.tig > testresults/chap2/test33.txt
./chap2/lextest testcases/test34.tig > testresults/chap2/test34.txt
./chap2/lextest testcases/test35.tig > testresults/chap2/test35.txt
./chap2/lextest testcases/test36.tig > testresults/chap2/test36.txt
./chap2/lextest testcases/test37.tig > testresults/chap2/test37.txt
./chap2/lextest testcases/test38.tig > testresults/chap2/test38.txt
./chap2/lextest testcases/test39.tig > testresults/chap2/test39.txt
./chap2/lextest testcases/test40.tig > testresults/chap2/test40.txt
./chap2/lextest testcases/test41.tig > testresults/chap2/test41.txt
./chap2/lextest testcases/test42.tig > testresults/chap2/test42.txt
./chap2/lextest testcases/test43.tig > testresults/chap2/test43.txt
./chap2/lextest testcases/test44.tig > testresults/chap2/test44.txt
./chap2/lextest testcases/test45.tig > testresults/chap2/test45.txt
./chap2/lextest testcases/test46.tig > testresults/chap2/test46.txt
./chap2/lextest testcases/test47.tig > testresults/chap2/test47.txt
./chap2/lextest testcases/test48.tig > testresults/chap2/test48.txt
./chap2/lextest testcases/test49.tig > testresults/chap2/test49.txt
./chap2/lextest testcases/merge.tig > testresults/chap2/merge.txt
./chap2/lextest testcases/queens.tig > testresults/chap2/queens.txt

echo Finished lexical tests
